name: Scraper

on:
  schedule:
    
    - cron: '0 21 * * *'
  workflow_dispatch: 

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Execute shell script
      run: bash populate.sh
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_URL: ${{ secrets.API_URL }}
